name: Restrict Changes

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for changed files detection

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35

      - name: Check for unauthorized changes
        run: |
          echo "Checking for unauthorized changes..."
          UNAUTHORIZED_CHANGES=false
          
          # Loop through all changed files
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            # Skip files in the devices directory
            if [[ $file =~ ^devices/ ]]; then
              echo "✅ Authorized change: $file"
              continue
            fi
            
            # Check if the user is a repository maintainer
            if [[ "${{ github.actor }}" == "maintainer1" || "${{ github.actor }}" == "maintainer2" ]]; then
              echo "⚠️ Maintainer change outside devices/: $file (allowed)"
              continue
            fi
            
            # Unauthorized change
            echo "❌ Unauthorized change outside devices/: $file"
            UNAUTHORIZED_CHANGES=true
          done
          
          if [[ "$UNAUTHORIZED_CHANGES" == "true" ]]; then
            echo "::error::Pull request contains unauthorized changes outside the devices/ directory"
            exit 1
          fi
          
          echo "✅ All changes are authorized"